name: akash-universal-solutions
static_sites:
- name: akash-universal-solutions
  github:
    repo: adishakash/Akash-Universal-Solutions-Business
    branch: main
    deploy_on_push: true
  build_command: npm run build
  output_dir: build
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  routes:
  - path: /
  domains:
  - domain: akashuniversalsolutions.com
    type: PRIMARY
  - domain: www.akashuniversalsolutions.com
    type: ALIAS
  cors:
    allow_origins:
    - exact: https://akashuniversalsolutions.com
    - exact: https://www.akashuniversalsolutions.com
    allow_methods:
    - GET
    - POST
    - OPTIONS
    allow_headers:
    - Content-Type
    - Authorization
